server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: wso2
    static_configs:
      - targets:
          - localhost
        labels:
          job: wso2
          service: wso2-am
          __path__: /home/wso2carbon/wso2am-4.3.0/repository/logs/*.log

  - job_name: wso2-traffic
    static_configs:
      - targets:
          - localhost
        labels:
          job: wso2-traffic
          __path__: /home/wso2carbon/wso2am-4.3.0/repository/logs/http_access*.log