server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: wso2
    static_configs:
      - targets:
          - localhost
        labels:
          job: wso2
          service: wso2-am
          __path__: /home/wso2carbon/wso2am-4.5.0/repository/logs/*.log

  - job_name: wso2-traffic
    static_configs:
      - targets:
          - localhost
        labels:
          job: wso2-traffic
          __path__: /home/wso2carbon/wso2am-4.5.0/repository/logs/http_access*.log

  - job_name: splp-gw
    static_configs:
      - targets:
          - localhost
        labels:
          container: splp-gw
          service: wso2-am
          __path__: /home/wso2carbon/wso2am-4.5.0/repository/logs/*.log

    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} '
      - regex:
          expression: '^TID: \[\] \[\] \[(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\]\s+(?P<level>[A-Z]+)\s+\{org\.wso2\.am\.analytics\.publisher\.sample\.reporter\.LogCounterMetric\} - (?P<msg>.*)$'
      - template:
          source: msg
          template: |
            {"log":"[{{ .ts }}] {{ .level }} - LogCounterMetric {{ .msg }}","stream":"stdout","time":"{{ .ts }}"}
      - output:
          source: msg
